import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Header } from "./_components/header"
import { Footer } from "./_components/footer"
import "./global.css";

const inter = Inter({
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Portfolio Ramon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter} antialiased `}
      >
   <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
